# Site settings
title: Khaled Zaky
header-img: img/home-bg.jpg
email: zakykhaled@gmail.com
copyright_name: Khaled Zaky
description: "My personal blog covering the latest technology trends, my passion porjects, and geek talk!"
baseurl: ""
url: "http://www.KhaledZaky.com"
twitter_username: iamkhaledzaky
github_username: kzaky
facebook_username:  kzaki
linkedin_username: khaledzaky
email_username: zakykhaled@gmail.com
instagram_username: kzaky

#Facebook Sharing
facebook_app_id: 1492818217458261

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["README.md", vendor]

gems: [jekyll-paginate, jekyll-feed]

# Resume settings
resume_name:  "Khaled Zaky"
resume_title: "Technical Product Manager|Software Engineer|TechGeek"
resume_header_intro: "<p>I describe myself as an innovative and self-motivated individual passionate about technology and software. My unique skills and think-outside-the-box approach play a significant role in my ability to bridge the gap between technology and businesses.  My strongest skill is working well with customers and understanding what problems the product is intended to solve. I have a great ability motivate my peers to achieve favorable results for complex initiatives.</p>
<p>I currently work for one of the big banks in Canada to define the cloud strategy and articulate the product vision from the highest levels of executive leadership to development and implementation teams. Prior to working in the financial sector, I managed an entire set of cloud products for the biggest telecommunications provider in Canada.</p>"

# which sections to use
resume_section_experience:  true
resume_section_education: true
resume_section_projects:  false
resume_section_skills:  false
resume_section_certifications:  true
resume_section_volunteer: true

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
